params:
  algo:
    name: a2c_continuous
  config:
    bounds_loss_coef: 0.0
    clip_actions: false
    clip_value: true
    critic_coef: 2
    e_clip: 0.2
    entropy_coef: 0.001
    env_name: Bittle
    full_experiment_name: Bittle2024-08-21-22:08:46
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 24
    kl_threshold: 0.008
    learning_rate: 0.0003
    lr_schedule: adaptive
    max_epochs: 1500
    mini_epochs: 5
    minibatch_size: 8192
    mixed_precision: true
    name: Bittle
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    num_actors: 1024
    player:
      games_num: 1
    ppo: true
    print_stats: true
    reward_shaper:
      scale_value: 1.0
    save_best_after: 0
    save_frequency: 500
    score_to_win: 20000
    seq_len: 4
    tau: 0.95
    truncate_grads: true
    value_bootstrap: true
  load_checkpoint: false
  load_path: null
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: relu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 400
      - 400
    name: actor_critic
    rnn:
      before_mlp: false
      concat_input: true
      layer_norm: false
      layers: 1
      name: lstm
      units: 256
    separate: true
    space:
      continuous:
        fixed_sigma: false
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0.0
  seed: 42
